### ISSUE TITLE
IndexOutOfBoundsException while moving through Search Everywhere popup in IDEA 2017.2.1

### ISSUE THREAD

**Issue by EkaterinaValeeva** [dkandalov/ijkl-shortcuts-plugin#2]
After installing the plugin v.1.1 and restarting the IDE tried Alt + I,J,K,L to navigate in Editor, File Structure popup (Ctrl+F12) and then Search Everywhere. 
For first two it seemed to work, in the third gave

`Index: 2, Size: 2
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.intellij.ide.actions.SearchEverywhereAction$18.actionPerformed(SearchEverywhereAction.java:956)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:621)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at ijkl.IjklEventDispatcher.dispatch(event-redispatch.kt:73)
	at ijkl.IjklIdePopupEventDispatcher.dispatch(event-redispatch.kt:50)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:97)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:600)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by dkandalov** [comment]
Do you have exact version of IDE?
And can you please try the latest version of IDE.

I've seen similar errors but was not able to reproduce them in 2017.2.2 (Build #IU-172.3757.29, built on August 8, 2017). My guess is that it could be IDE errors reported as plugin error because of the plugin package on stacktrace (I might wrong about that though).

**Comment by EkaterinaValeeva** [comment]
2017.2.2 does not have this issue indeed. Thank you for the hint.

**Comment by dkandalov** [comment]
Glad it helped. Thanks a lot for reporting the issue (it can be really useful just for reference and in case somebody else has the same problem).
